workflows:
    react-native-android:
        name: React Native Android
        environment:
            vars:
                TRIBL_SERVER_BASE_URI: Encrypted(Z0FBQUFBQmZ5NWlwaGh3U2xMZTNYR0dWS2pCRXV3NHJGQjlhQ1BEWG5nNG56dWxLRVNwS1RFTzBEMXNjOElaNE4wejR3N0duT2VobGxickluNEFEc2k3TGxPSGc4Z0RkYXFUazF1N09ZV2swc0NUZWFJaXQwNzIzdXphRzBiWWFhMWVwN1lxa2pZcXk0R2dKRDJFUzA2cjV3NV9zbnB1TnpRPT0=)
                TRIBL_WSS_SERVER_BASE_URI: Encrypted(Z0FBQUFBQmZ5NWdtVF9LbXN4RzhXTnFWOExNRWx5ak9pcU5ocFRiZmN2MEE2UVYwYTRHd0N1WmNYMnBFeDdhUENybVNnLWZVNmxRdExQdWVfSUNRb0dTQ013aDBuam5qWVE0dFlhYXFrVEh4RXI3SjlKVUg5NjdLUmt5YU5zdExiN3pzUzRYMjVRRjI3UEFCbWRlcDdnVXlJTUZaYU5nT0xKTTRGaDNDZDVVV181UnlhWXVXWXBVPQ==)
                GOOGLE_PLACES_API: Encrypted(Z0FBQUFBQmZ5NWVJUjFSMXhxS0tvYklSeXNtWkFmVF9DZnRPTlpRcjJpRGJRNkx0Rm56ai11RDVZYTFJNENzX1pQY3NaZUhFMEVKeTFuNDhrT1QzaTctbnpOdWFzYm1wSW9lTWxfNXNLbUotdk9XdGJvTzJIaWNqV0tuWHZ4VlVmaUoxb01ERjYzbUM=)
                CLOUDINARY_NAME: Encrypted(Z0FBQUFBQmZ5NWNvSjF1d1NUMGNXWHFRam55eVpoMUNMQXRfNXVFeGNCNGxDSy1BcGJZTVBYT0o0bXlabUVTNGpvTjEzLUpNMEJId0pNN0l3eHdkS3YtZEpUaXVYb3pGby1vNU5sVzdlem0zZmdmV240aHhLS1E9)
                CLOUDINARY_PRESET: Encrypted(Z0FBQUFBQmZ5NWJOQTB2VmxDd3hXSVdQUlVqZC16b0x1akQtbThpV1FseWZIRkRkOU9uN0tfTEYtYXR6S1BSazFyUVBlY2RaNWpiMTdaOG5reUhWcEVvY3Q2LUdJTjlaaVE9PQ==)
                SENTRY_KEY: Encrypted(Z0FBQUFBQmZ5NWFhYll6b3llNEhoUXhrWVhKUldFTXM4MUZSUkZ6UUdnUmxRWi02aDBkaFFXa3d3dlk5bFhyQ3FiQ0s3ODE0Ym9UNXJlWHRaeU9mMXdmZDJTbWhaYU5aU0NLVzNPVEEwSkhMMDd5YVJTVVAxaFBxcU1SSzlJMWJzUHlGdEY5MGZLX3lIc0ZmZXpyM1ZsbkN4TlBFQ0hCc3FYTzZEOURMRnAtYklSTXdXVGNudjNFPQ==)
                ALGOLIA_PASSPORT_INDEX_NAME: Encrypted(Z0FBQUFBQmZ5NVlmOC0tSkRtaFNUOEJlVlNSNTZ0aTNTZ3FoQll4eUFaRm1leDlMUVl1bHE0aTVZa21Ld0oxSHAyRlcyTXROMzNNdnZ6dngzeHBTZjJRTFVDTTVzOHZ2YzVSbFhUTDBNbFBWZUdiclgwZjNkNXM9)
                ALGOLIA_COMMUNITY_INDEX_NAME: Encrypted(Z0FBQUFBQmZ5NVhqMDd0YUY4bGl4ZmVjLVhGb096TXBJU3BKVjdubU8zNExnUU5uU041a0g1UXd3cGtBd2ZURUhGWTB2QWVRdjRWUW9YYnFnQ1poS3pacEtKSFVFaUY4dXB0UmlKNWRMLUpISkVCS2xiTmY5cDg9)
                ALGOLIA_COMMUNITY_MEMBERS_INDEX_NAME: Encrypted(Z0FBQUFBQmZ5NVdIOG90c3FWVmc0cnBtVVdpNVJZcUszOVB3SVZROHRHdXhvdXZyb1ROWnI3b0RTcHZyeXplSVBkc2R3RGEtYzFpTWJKcTBzbERIU1VXd2RrbS1VZndxaThETlBra2NHUnBkUk5hcl9jSXRxbjA9)
                ALGOLIA_PASSPORT_LOCATION_INDEX_NAME: Encrypted(Z0FBQUFBQmZ5NVRjVXlqSVF6TWY2MGdOelU4SXBKem45QmFBek0yQkRycm9ZbndWQkVRbWxseFJfRFR4QlI4a0xoMG1HbUM2MnlrbjVEd2YxWUZkRmg2NXpDLVNjbm5zeVRRZzJjTGhWMUw2ZU9kQ3NHTU9Eam89)
                FIREBASE_PROJECT_ID: Encrypted(Z0FBQUFBQmZ5NVNmQjJjQWNPVzI1SDduX19pdFF4LTlzTE13VW16OTlUT25WcUZTVVF1YzdXMEJZc2NOaGhaeEtJdlJNSFZ3Q0xFcm1JSUwyQS1DakNqWlg4VHdwQklOYlE9PQ==)
                FIREBASE_MEASUREMENT_ID: Encrypted(Z0FBQUFBQmZ5NVF4bUdmb19oU01oLVE2dHl6d0ZXSGotaUEwR2QxZmd6ekN6aTVWbGEzX2oyUW9Ra1pHLW9ST3U2YWpTUEJuRnRQNzVqUmx6N0oxekF5UEZEVDBjemJHa0E9PQ==)
                FIREBASE_MESSAGING_SENDER_ID: Encrypted(Z0FBQUFBQmZ5NVBTbFYxMTRlaGdIdncyMVNmV1ZESDA4T3hrRmFCTTJnRUhzYmh6VWFMRUNOY1FFOXZKNGI1bGlNZElSSUhONmFTTTlwNXpsLUZEVVpBRUczTlFSNGh3RGc9PQ==)
                FIREBASE_STORAGE_BUCKET: Encrypted(Z0FBQUFBQmZ5NU5wUnRHNDllbkFzOGJpUTlCbTRWR2czN3RnVmRQaC0yZmluZnNYNExYaG9jdEJ6VTd2eW9saUlqMzFNckdsb3o0YkZlalNDTFNSTWJ1cEJITGlfODVLbDB3TnNkcWFNZzBFbjhscGlQbXlINTQ9)
                FIREBASE_AUTH_DOMAIN: Encrypted(Z0FBQUFBQmZ5NU9pX1hGaHdHc2VKTVZCMGJ6RjNrbjhvNXM3R015Z0VJeGZ1WnlVWFQ1LVhlU0ZyWkFIRXUybGlKUUxlNjk0UlkxX2Z0MTlGYUMwYXdEd0wybkg5blhscVplUm1UTklILUdlT19uTVlqVWhIQkE9)
                FIREBASE_API_KEY: Encrypted(Z0FBQUFBQmZ5NU1OMVF4TWJQYmlTY2Fvbnh4S3JzcUhDWTRiei1zaXhiRTVhdVRYY2pKZndkbDhCU0NUMElhMVBvLWJVaHVqYkVqdDU5Nm0ydE41RzdwRGJTTDdpbFZFNmM2RlR3V2kteUNfWEVSMC14Q0tqSzBORlhZODlGbWJQS2Y0RHA3UjhzREw=)
                FIREBASE_APP_ID: Encrypted(Z0FBQUFBQmZ5NUs5Z2FxRE1TOGtVZU1OYkljMVR5YXAzM0tVQkkxWUZfck1KdW45VkV4UEhwM3J4dnF6cWFvMVR2UmxsQzQ0elc4OGlleEx1V2pVLTlqbEEyal9HWXZGR0tBNVJGQUd5aWtyYTBJeGV4NzdKZ1JkaEUwMkhHRUY4dDFZSTlMSXFFTmw=)
                FIREBASE_DATA_BASEURL: Encrypted(Z0FBQUFBQmZ5NUlmM2QxeWowNEhOVUZ3dEQ4MG4tUWVJdnllUG1reXF0NWxudGNDRUZXWjRsR3g0R21GZldDQ2F6NnJKWjZOOHJiVTZxVnRjeGRremhPd1JKV0ZjT29NUjVtb0pJenVpbmNjZ3R3XzZSZExrVFFHb1ZOU1A4NDZUWjVZcGIweDhoQmM=)
                TRIBL_UX_CAM: Encrypted(Z0FBQUFBQmZ5NUdxeDhNQS14elRWamUxbWpfQ0VqU2hucGQwSHo4bVFGdnFydVg2eWVneG5saWZMVUdPQnVZVHZrcjdJMTN4YWMwRDN1SmhHa3lOdGZxemU1MXYzdzM2bHc9PQ==)
                TRIBL_MIX_PANEL: Encrypted(Z0FBQUFBQmZ5NUYwUnZWdHBFaUNYQWRETWdtOUphSlNyZXNLS0hLRGNGRU8tdnppcjA0LVdraHNETy1zMDRuUzYwMDdpaExpMmwxYUtlMnpDUkpNbjFYV2pPWkw4VnJTZE5lcmR5ZVJjRzY5dGJNMXE3VWp3V0RNalhidGVTMW05cEpmdEtzR3NKV0Q=)
                TRIBL_ALGOLIA_APP_ID: Encrypted(Z0FBQUFBQmZ5NUVVUzY4eU5Fd2gyZUI3Q2tsM3hfMjhsbzF0cFN3ZVMzZTdzbzloQjc3dWtDQVZzUGRMai13eWxGUEhzZ0FQQm1zdEFfSkNteTVLcHNuVnhlUkNVOUlhOGc9PQ==)
                TRIBL_ALGOLIA_API_KEY: Encrypted(Z0FBQUFBQmZ5NURUbjVkM0NaSHdRcmlaWkd2endDU3Q3QmgwdHlNc1daWXFBNnVqRGlnVWRNMldROTNrVW96WGtEdWxfNWlxN2Z4aGsxaDl3WG5uZXhPUzNpSnE5ZGJlSE5BTXRhOHhJU01wcGY0ZHVaemljdkgyRDFZM3NYbVFYRmVxcFR1Nm9mNzA=)
                APP_VERSION_CODE: 101033
                APP_VERSION_NAME: 1.2.2
                CM_KEYSTORE: Encrypted(Z0FBQUFBQmZ5bjc3SFB3Z212NFBxVWdXOV83ZWFRd2tVSEFUaWN5VlFDM0VoSjhsOXFMNmZjTElPRlJscVdFUUtwMWdaNEhGajEzQnN3LWw1cmdIWGJrMHpESUxLYUpFNVE9PQ==) # <-- Put your encrypted keystore file here
                CM_KEYSTORE_PASSWORD: Encrypted(Z0FBQUFBQmZ5bjlkdGppMXp5LXloaUFWYkRhSHVQNU01RXg2alNUTGI2T2tXVnQ5dmJoTUp2enJ0aGU1TmNsME9NcU5XVWQxTnd2VHdPR2E1bEJuSHhSa3hUaFYtZWl2aGc9PQ==) # <-- Put your encrypted keystore password here
                CM_KEY_ALIAS_PASSWORD: Encrypted(Z0FBQUFBQmZ5bjlkdGppMXp5LXloaUFWYkRhSHVQNU01RXg2alNUTGI2T2tXVnQ5dmJoTUp2enJ0aGU1TmNsME9NcU5XVWQxTnd2VHdPR2E1bEJuSHhSa3hUaFYtZWl2aGc9PQ==) # <-- Put your encrypted keystore alias password here
                CM_KEY_ALIAS_USERNAME: Encrypted(Z0FBQUFBQmZ5bjh6OWRwd3huMnhOaVp0TkxEOW11YkNVOXlKVV9RTUNBdms5eDJISF9PTkVFVmVFS2MtazdYNWRvNFZMejBQNVRpRUl2cTA3MGlJSVZkSF90bDJHWVpuekE9PQ==) # <-- Put your encrypted keystore alias username here
            node: latest
        triggering:
            events:
                - push
                - tag
                - pull_request
            branch_patterns:
                - pattern: develop # <<-- put the branch that the codemagic config file is
                  include: true
                  source: true
        scripts:
            - name: Install yarn dependencies
              script: |
                 yarn
            - name: Set Android SDK location
              script: |
                echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
            - name: Set up keystore
              script: |
                 echo 'APP_VERSION_CODE=$APP_VERSION_CODE.
                 APP_VERSION_NAME=$APP_VERSION_NAME'>.env
#                     echo $CM_KEYSTORE | base64 --decode > /tmp/android/app/tribl.keystore
#                     cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
#                     storePassword=$CM_KEYSTORE_PASSWORD
#                     keyPassword=$CM_KEY_ALIAS_PASSWORD
#                     keyAlias=$CM_KEY_ALIAS_USERNAME
#                     storeFile=/tmp/keystore.keystore
#                     EOF
            - name: Build Android release
              script: |
                # build Android
                cd android 
                ./gradlew assembleRelease
        artifacts:
            - android/app/build/outputs/**/*.apk
        publishing:
            google_play:                        # For Android app
                 credentials:  # Put your encrypted JSON key file for Google Play service account
                 track: alpha 
            email:
                recipients:
                    - john.doe@gmail.com # Put your email address for build notifications (optional)
