workflows:
    react-native-android:
        name: React Native Android
        environment:
            vars:
                CM_KEYSTORE: Encrypted(Z0FBQUFBQmZ5bjc3SFB3Z212NFBxVWdXOV83ZWFRd2tVSEFUaWN5VlFDM0VoSjhsOXFMNmZjTElPRlJscVdFUUtwMWdaNEhGajEzQnN3LWw1cmdIWGJrMHpESUxLYUpFNVE9PQ==) # <-- Put your encrypted keystore file here
                CM_KEYSTORE_PASSWORD: Encrypted(Z0FBQUFBQmZ5bjlkdGppMXp5LXloaUFWYkRhSHVQNU01RXg2alNUTGI2T2tXVnQ5dmJoTUp2enJ0aGU1TmNsME9NcU5XVWQxTnd2VHdPR2E1bEJuSHhSa3hUaFYtZWl2aGc9PQ==) # <-- Put your encrypted keystore password here
                CM_KEY_ALIAS_PASSWORD: Encrypted(Z0FBQUFBQmZ5bjlkdGppMXp5LXloaUFWYkRhSHVQNU01RXg2alNUTGI2T2tXVnQ5dmJoTUp2enJ0aGU1TmNsME9NcU5XVWQxTnd2VHdPR2E1bEJuSHhSa3hUaFYtZWl2aGc9PQ==) # <-- Put your encrypted keystore alias password here
                CM_KEY_ALIAS_USERNAME: Encrypted(Z0FBQUFBQmZ5bjh6OWRwd3huMnhOaVp0TkxEOW11YkNVOXlKVV9RTUNBdms5eDJISF9PTkVFVmVFS2MtazdYNWRvNFZMejBQNVRpRUl2cTA3MGlJSVZkSF90bDJHWVpuekE9PQ==) # <-- Put your encrypted keystore alias username here
            node: latest
        triggering:
            events:
                - push
                - tag
                - pull_request
            branch_patterns:
                - pattern: develop # <<-- put the branch that the codemagic config file is
                  include: true
                  source: true
        scripts:
            - name: Install yarn dependencies
              script: |
                yarn
            - name: Set Android SDK location
              script: |
                echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
            - name: Set up keystore
              script: |
                    echo $CM_KEYSTORE | base64 --decode > /tmp/android/app/tribl.keystore
                    cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
                    storePassword=$CM_KEYSTORE_PASSWORD
                    keyPassword=$CM_KEY_ALIAS_PASSWORD
                    keyAlias=$CM_KEY_ALIAS_USERNAME
                    storeFile=/tmp/keystore.keystore
                    EOF
            - name: Build Android release
              script: |
                # build Android
                cd android 
                ./gradlew assembleRelease
        artifacts:
            - android/app/build/outputs/**/*.apk
        publishing:
            google_play:                        # For Android app
                credentials: Encrypted(...)  # Put your encrypted JSON key file for Google Play service account
                track: alpha 
            email:
                recipients:
                    - john.doe@gmail.com # Put your email address for build notifications (optional)
    
    react-native-ios:
        name: React Native iOS
        max_build_duration: 120
        instance_type: mac_mini
        environment:
            vars:
                XCODE_WORKSPACE: "codemagicreactnative.xcworkspace" # <-- Put the name of your Xcode workspace here
                XCODE_SCHEME: "codemagicreactnative" # <-- Put the name of your Xcode scheme here
                # Manual Code Signing
                # CM_CERTIFICATE: Encrypted(...) # <-- Put your encrypted certificate file here
                # CM_CERTIFICATE_PASSWORD: Encrypted(...) # <-- Put your encrypted certificate password here
                # CM_PROVISIONING_PROFILE: Encrypted(...) # <-- Put your encrypted provisioning profile here
                
                # Automatic Code Signing 
                # https://docs.codemagic.io/yaml/distribution/
                # https://appstoreconnect.apple.com/access/api
                APP_STORE_CONNECT_ISSUER_ID: 5a451239-51eb-10b6-bfcc-60e61ddab13c # <-- Put your App Store Connect Issuer Id here
                APP_STORE_CONNECT_KEY_IDENTIFIER: LY55E1G322 # <-- Put your App Store Connect Key Identifier here
                APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...) # <-- Put your App Store Connect Private Key here
                CERTIFICATE_PRIVATE_KEY: Encrypted(...) # <-- Put your Certificate Private key here
            node: latest
            xcode: latest
            cocoapods: default
        triggering:
            events:
                - push
                - tag
                - pull_request
            branch_patterns:
                - pattern: develop # <<-- put the branch that the codemagic config file is
                  include: true
                  source: true
        scripts:
            - name: Install npm dependencies
              script: |
                npm install
            - name: Install CocoaPods dependencies
              script: |
                cd ios && pod install
            - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
              script: |
                keychain initialize
            # - name: Set up Provisioning profiles from environment variables (Use with manual code signing)
              # script: |
                # PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
                # mkdir -p "$PROFILES_HOME"
                # PROFILE_PATH="$(mktemp "$PROFILES_HOME"/$(uuidgen).mobileprovision)"
                # echo ${CM_PROVISIONING_PROFILE} | base64 --decode > $PROFILE_PATH
                # echo "Saved provisioning profile $PROFILE_PATH"
            - name: 
              script: |  
                app-store-connect fetch-signing-files "com.codemagicreactnative" --type IOS_APP_ADHOC --create
            # - name: Set up signing certificate (Use with manual code signing)
            #   script: |
            #     echo $CM_CERTIFICATE | base64 --decode > /tmp/certificate.p12
            #     keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password $CM_CERTIFICATE_PASSWORD
            - name: Use system default keychain
              script: |
                keychain add-certificates
            - name: Increment build number
              script: |
                #!/bin/sh
                set -e
                set -x
                cd $FCI_BUILD_DIR/ios
                agvtool new-version -all $(($BUILD_NUMBER + 1))
            - name: Set up code signing settings on Xcode project
              script: |
                xcode-project use-profiles
            - name: Build ipa for distribution
              script: |
                xcode-project build-ipa --workspace "$FCI_BUILD_DIR/ios/$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
        artifacts:
            - build/ios/ipa/*.ipa
            - /tmp/xcodebuild_logs/*.log
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

        publishing:
          app_store_connect:                 
              apple_id: yourAppleId@example.com  
              password: Encrypted(...) # <-- Put your App Specific Password. For more information visit: https://support.apple.com/en-us/HT204397
          email:
            recipients:
                - john.doe@gmail.com
     
